spring.application.name=social-action-network

# Este puerto sera con el que trabajaremos
server.port=9000

# Conexion a base de datos
spring.data.mongodb.uri=mongodb://localhost:27017/Social_Action_Network