
#config mongo

spring.data.mongodb.database=registros
spring.data.mongodb.uri=mongodb://localhost:27017/registos



spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# configuracion del modelo
spring.ai.openai.base-url=http://localhost:11434
spring.ai.openai.chat.options.model=llama3:latest
spring.ai.openai.api-key=local